import type { CardConfig } from "@/types/card";

export const cardConfig: CardConfig = {
  profile: {
    name: "Gregorio V. Cano",
    title: "Allure Studio Owner",
    tagline: "Aesthetic excellence, naturally beautiful results",
    avatar: "https://picsum.photos/seed/avatar1/400/400",
    cover: "/assets/Bg.jpg",
    bio:
      "With over 15 years of experience in medical aesthetics, Dr. Mitchell combines advanced techniques with an artistic eye to deliver personalized treatments that enhance your natural beauty. Every treatment plan is tailored to your unique goals, ensuring results that look and feel like you.",
  },
  contact: {
    phone: "+1-555-0142",
    email: "hello@studioname.com",
    website: "https://www.studioname.com",
    address: "123 Wellness Avenue, Suite 200, Beverly Hills, CA 90210",
  },
  primaryCta: "Book Consultation",
  socials: [
    { platform: "Instagram", url: "https://instagram.com/studioname", icon: "Instagram" },
    { platform: "Facebook", url: "https://facebook.com/studioname", icon: "Facebook" },
    { platform: "TikTok", url: "https://tiktok.com/@studioname", icon: "Tiktok" },
    { platform: "YouTube", url: "https://youtube.com/@studioname", icon: "Youtube" },
  ],
  services: [
    {
      id: "s1",
      title: "Injectable Treatments",
      description: "Expertly administered dermal fillers and neuromodulators for smooth, youthful-looking skin.",
      image: "https://picsum.photos/seed/service1/400/300",
      category: "Face",
    },
    {
      id: "s2",
      title: "Skin Resurfacing",
      description: "Advanced laser and chemical peel treatments to renew skin texture and tone.",
      image: "https://picsum.photos/seed/service2/400/300",
      category: "Skin",
    },
    {
      id: "s3",
      title: "Body Contouring",
      description: "Non-invasive fat reduction and skin-tightening technologies for a sculpted silhouette.",
      image: "https://picsum.photos/seed/service3/400/300",
      category: "Body",
    },
    {
      id: "s4",
      title: "IV Wellness Therapy",
      description: "Customized vitamin and nutrient infusions to boost energy, immunity, and overall vitality.",
      image: "https://picsum.photos/seed/service4/400/300",
      category: "Wellness",
    },
  ],
  offers: [
    {
      id: "o1",
      title: "New Client Consultation",
      description: "Comprehensive assessment and personalized treatment plan with our medical director.",
      price: "Complimentary",
      image: "https://picsum.photos/seed/offer1/400/300",
    },
    {
      id: "o2",
      title: "Radiance Package",
      description: "3-session bundle combining HydraFacial, microneedling, and LED light therapy.",
      price: "$450",
      image: "https://picsum.photos/seed/offer2/400/300",
      badge: "Most Popular",
    },
  ],
  process: [
    {
      id: "p1",
      title: "Consultation",
      description: "We listen to your goals and assess your needs in a private, comfortable setting.",
      icon: "MessageCircle",
      image: "https://picsum.photos/seed/process1/400/300",
    },
    {
      id: "p2",
      title: "Treatment Plan",
      description: "A customized plan is created, reviewed, and approved before any procedure begins.",
      icon: "ClipboardList",
      image: "https://picsum.photos/seed/process2/400/300",
    },
    {
      id: "p3",
      title: "Aftercare",
      description: "Ongoing support and follow-up care to ensure optimal, lasting results.",
      icon: "Heart",
      image: "https://picsum.photos/seed/process3/400/300",
    },
  ],
  results: [
    {
      id: "r1",
      before: "https://picsum.photos/seed/before1/400/400",
      after: "https://picsum.photos/seed/after1/400/400",
      alt: "Skin resurfacing before and after",
    },
    {
      id: "r2",
      before: "https://picsum.photos/seed/before2/400/400",
      after: "https://picsum.photos/seed/after2/400/400",
      alt: "Body contouring before and after",
    },
    {
      id: "r3",
      before: "https://picsum.photos/seed/before3/400/400",
      after: "https://picsum.photos/seed/after3/400/400",
      alt: "Injectable treatment before and after",
    },
  ],
  testimonials: [
    {
      id: "t1",
      name: "Emily R.",
      text: "Incredibly professional and attentive. The results exceeded my expectations and the whole experience was so relaxing.",
      rating: 5,
      avatar: "https://picsum.photos/seed/avatar2/100/100",
    },
    {
      id: "t2",
      name: "Michael T.",
      text: "I finally feel like myself again. The team took the time to understand exactly what I wanted and delivered beautifully.",
      rating: 5,
      avatar: "https://picsum.photos/seed/avatar3/100/100",
    },
    {
      id: "t3",
      name: "Jessica L.",
      text: "The atmosphere is luxurious and calming. Every visit feels like a retreat. Highly recommend to anyone considering treatment.",
      rating: 5,
      avatar: "https://picsum.photos/seed/avatar4/100/100",
    },
  ],
  locations: [
    {
      id: "l1",
      name: "Main Studio",
      address: "123 Wellness Avenue, Suite 200, Beverly Hills, CA 90210",
      hours: "Mon-Fri: 9am - 6pm, Sat: 10am - 4pm",
      mapUrl: "https://maps.google.com",
    },
    {
      id: "l2",
      name: "Downtown Lounge",
      address: "456 City Center Blvd, Los Angeles, CA 90015",
      hours: "Mon-Fri: 10am - 7pm, Sat: 10am - 3pm",
      mapUrl: "https://maps.google.com",
    },
  ],
  formFields: [
    { name: "name", label: "Full Name", type: "text", placeholder: "Your full name", required: true },
    { name: "phone", label: "Phone Number", type: "tel", placeholder: "+1-555-0000", required: true },
    { name: "location", label: "Preferred Location", type: "select", placeholder: "Select a location", required: true },
    { name: "date", label: "Preferred Date", type: "date", placeholder: "", required: true },
  ],
  qr: {
    url: "https://www.studioname.com",
    vCard: "BEGIN:VCARD\nVERSION:3.0\nFN:Dr. Sarah Mitchell\nTITLE:Medical Director\nTEL:+1-555-0142\nEMAIL:hello@studioname.com\nEND:VCARD",
  },
  sectionTitles: {
    about: "About",
    services: "Services",
    offers: "Special Offers",
    process: "Our Process",
    results: "Results",
    testimonials: "Testimonials",
    locations: "Locations",
    booking: "Book Now",
  },
  sections: {
    hero: true,
    contactActions: true,
    socialLinks: true,
    about: true,
    services: true,
    offers: true,
    process: true,
    resultsGallery: true,
    testimonials: true,
    locations: true,
    bookingForm: true,
  },
  footerText: "© 2024 Studio Name. All rights reserved.",
};
