import type { CardConfig } from "@/types/card";

export const cardConfig: CardConfig = {
  profile: {
    clinicName: "Allure Aesthetic Clinic",
    name: "Gregorio V. Cano",
    title: "Aesthetic Practitioner",
    tagline: "Natural-looking results. Personalized aesthetic care.",
    avatar: "/assets/Profile.jpg",
    cover: "/assets/Bg.jpg",
    bio:
      "With over 15 years of experience in medical aesthetics, Gregorio combines advanced techniques with an artistic eye to deliver personalized treatments that enhance your natural beauty. Every treatment plan is tailored to your unique goals, ensuring results that look and feel like you.",
  },
  contact: {
    phone: "+1-555-0142",
    email: "hello@allureclinic.com",
    website: "https://www.allureclinic.com",
    address: "Calbayog City, Samar",
  },
  primaryCta: "Book Consultation",
  services: [
    {
      id: "s1",
      title: "Injectable Treatments",
      description: "Expertly administered dermal fillers and neuromodulators for smooth, youthful-looking skin.",
      image: "https://picsum.photos/seed/service1/800/600",
      category: "Face",
    },
    {
      id: "s2",
      title: "Skin Resurfacing",
      description: "Advanced laser and chemical peel treatments to renew skin texture and tone.",
      image: "https://picsum.photos/seed/service2/800/600",
      category: "Skin",
    },
    {
      id: "s3",
      title: "Body Contouring",
      description: "Non-invasive fat reduction and skin-tightening technologies for a sculpted silhouette.",
      image: "https://picsum.photos/seed/service3/800/600",
      category: "Body",
    },
    {
      id: "s4",
      title: "IV Wellness Therapy",
      description: "Customized vitamin and nutrient infusions to boost energy, immunity, and overall vitality.",
      image: "https://picsum.photos/seed/service4/800/600",
      category: "Wellness",
    },
  ],
  offers: [
    {
      id: "o1",
      title: "New Client Consultation",
      description: "Comprehensive assessment and personalized treatment plan with our medical director.",
      price: "Complimentary",
      image: "https://picsum.photos/seed/offer1/800/600",
    },
    {
      id: "o2",
      title: "Radiance Package",
      description: "3-session bundle combining HydraFacial, microneedling, and LED light therapy.",
      price: "$450",
      image: "https://picsum.photos/seed/offer2/800/600",
      badge: "Most Popular",
    },
  ],
  process: [
    {
      id: "p1",
      title: "Consultation",
      description: "We listen to your goals and assess your needs in a private, comfortable setting.",
      icon: "MessageCircle",
      image: "https://picsum.photos/seed/process1/800/600",
    },
    {
      id: "p2",
      title: "Treatment Plan",
      description: "A customized plan is created, reviewed, and approved before any procedure begins.",
      icon: "ClipboardList",
      image: "https://picsum.photos/seed/process2/800/600",
    },
    {
      id: "p3",
      title: "Aftercare",
      description: "Ongoing support and follow-up care to ensure optimal, lasting results.",
      icon: "Heart",
      image: "https://picsum.photos/seed/process3/800/600",
    },
  ],
  results: [
    {
      id: "r1",
      before: "https://picsum.photos/seed/before1/800/800",
      after: "https://picsum.photos/seed/after1/800/800",
      alt: "Skin resurfacing before and after",
    },
    {
      id: "r2",
      before: "https://picsum.photos/seed/before2/800/800",
      after: "https://picsum.photos/seed/after2/800/800",
      alt: "Body contouring before and after",
    },
    {
      id: "r3",
      before: "https://picsum.photos/seed/before3/800/800",
      after: "https://picsum.photos/seed/after3/800/800",
      alt: "Injectable treatment before and after",
    },
  ],
  testimonials: [
    {
      id: "t1",
      name: "Emily R.",
      text: "Incredibly professional and attentive. The results exceeded my expectations and the whole experience was so relaxing.",
      rating: 5,
      avatar: "https://picsum.photos/seed/avatar2/100/100",
    },
    {
      id: "t2",
      name: "Michael T.",
      text: "I finally feel like myself again. The team took the time to understand exactly what I wanted and delivered beautifully.",
      rating: 5,
      avatar: "https://picsum.photos/seed/avatar3/100/100",
    },
    {
      id: "t3",
      name: "Jessica L.",
      text: "The atmosphere is luxurious and calming. Every visit feels like a retreat. Highly recommend to anyone considering treatment.",
      rating: 5,
      avatar: "https://picsum.photos/seed/avatar4/100/100",
    },
  ],
  locations: [
    {
      id: "l1",
      name: "Main Studio",
      address: "Calbayog City, Samar",
      hours: "Mon-Fri: 9am - 6pm, Sat: 10am - 4pm",
      mapUrl: "https://maps.google.com",
      timezone: "Asia/Manila",
    },
    {
      id: "l2",
      name: "Downtown Lounge",
      address: "Catarman, Northern Samar",
      hours: "Mon-Fri: 10am - 7pm, Sat: 10am - 3pm",
      mapUrl: "https://maps.google.com",
      timezone: "Asia/Manila",
    },
  ],
  formFields: [
    { name: "name", label: "Full Name", type: "text", placeholder: "Your full name", required: true },
    { name: "phone", label: "Phone Number", type: "tel", placeholder: "+1-555-0000", required: true },
    { name: "location", label: "Preferred Location", type: "select", placeholder: "Select a location", required: true },
    { name: "date", label: "Preferred Date", type: "date", placeholder: "", required: true },
  ],
  sectionTitles: {
    about: "About Allure",
    services: "Services",
    offers: "Special Offers",
    process: "Our Process",
    results: "Results",
    testimonials: "Testimonials",
    locations: "Our Locations",
    booking: "Book a Consultation",
  },
  sections: {
    hero: true,
    contactActions: true,
    about: true,
    services: true,
    offers: true,
    process: true,
    resultsGallery: true,
    testimonials: true,
    locations: true,
    bookingForm: true,
  },
  footerText: "© 2026 Allure Aesthetic Clinic. All rights reserved.",
};
